### ISSUE TITLE
oracle connection string

### ISSUE THREAD

**Issue by aborruso** [aswan89/visidata_plugin_genericSQL#2]
Hi,
I have run this command

```
vd oracle+cx_oracle://usr:pws
```

And I have an error "Non-existent file or directory: 'oracle+cx_oracle://usr:pws'. 

Probably I must check plugin installation

**Comment by aswan89** [comment]
Try removing the `+cx_oracle` section of the url, visidata doesn't handle that format of connection string properly. SQLAlchemy defaults to using cx_oracle for Oracle databases as it is so you don't need to specify the driver that way.

**Comment by aborruso** [comment]
I need to do a complex connection as the annoying case here https://gist.github.com/DGrady/7fb5c2214f247dcff2cb5dd99e231483#the-annoying-case

Then I have tried using

```
vd oracle://myuser:pwd@cx_Oracle.makedsn('172.11.12.24', '1521', service_name='name')
```

but I have `bash: syntax error near unexpected token `('`

If I run `vd oracle://myuser:pwd@cx_Oracle@name` I have

```
Traceback (most recent call last):
  File "/home/andrea.borruso/.local/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/main.py", line 213, in vd_cli
    rc = main_vd()
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/main.py", line 133, in main_vd
    vs = openSource(src)
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/vdobj.py", line 37, in _vdfunc
    return func(visidata.vd, *args, **kwargs)
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/data.py", line 157, in openSource
    return vd.openPath(Path(p), filetype=filetype)  # convert to Path and recurse
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/data.py", line 122, in openPath
    return getGlobals()[openfunc](p, filetype=filetype)
KeyError: 'openurl_oracle'
```

I'm able to connect to it via python in this way

```python
import cx_Oracle
import sqlalchemy
import pandas as pd
from sqlalchemy import create_engine

oracle_connection_string = (
    'oracle+cx_oracle://{username}:{password}@' +
    cx_Oracle.makedsn('{hostname}', '{port}', service_name='{service_name}')
)

engine = create_engine(
    oracle_connection_string.format(
        username='myusr',
        password='pwd',
        hostname='172.11.12.24',
        port='1521',
        service_name='name',
    )
)
```

Thank you

**Comment by aswan89** [comment]
> `bash: syntax error near unexpected token (`

That makes me wonder if you'd be able to just surround your connection string with quotes, if you don't bash will interpret the parentheses as part of a bash command.

ie. run `vd "oracle://myuser:pwd@cx_Oracle.makedsn('172.11.12.24', '1521', service_name='name')"`

**Comment by aborruso** [comment]
> ie. run `vd "oracle://myuser:pwd@cx_Oracle.makedsn('172.11.12.24', '1521', service_name='name')"`

Now I have

```
Traceback (most recent call last):
  File "/home/andrea.borruso/.local/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/main.py", line 213, in vd_cli
    rc = main_vd()
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/main.py", line 133, in main_vd
    vs = openSource(src)
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/vdobj.py", line 37, in _vdfunc
    return func(visidata.vd, *args, **kwargs)
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/data.py", line 157, in openSource
    return vd.openPath(Path(p), filetype=filetype)  # convert to Path and recurse
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/data.py", line 122, in openPath
    return getGlobals()[openfunc](p, filetype=filetype)
KeyError: 'openurl_oracle'
```

**Comment by aborruso** [comment]
If I do the same for a MySQL db

```
 vd mysql://name:pwd@DB
```

I have the same kind of error

```
Traceback (most recent call last):
  File "/home/andrea.borruso/.local/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/main.py", line 213, in vd_cli
    rc = main_vd()
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/main.py", line 133, in main_vd
    vs = openSource(src)
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/vdobj.py", line 37, in _vdfunc
    return func(visidata.vd, *args, **kwargs)
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/data.py", line 157, in openSource
    return vd.openPath(Path(p), filetype=filetype)  # convert to Path and recurse
  File "/home/andrea.borruso/.local/lib/python3.6/site-packages/visidata/data.py", line 122, in openPath
    return getGlobals()[openfunc](p, filetype=filetype)
KeyError: 'openurl_mysql'
```

**Comment by aswan89** [comment]
So this is related to how Visidata imports plugins in general. I installed the plugin manually and then added the line `from plugins.generic_sql import *` to `~/.visidatarc`. This adds the `openurl_` functions to the visidata init namespace properly. Try adding that line to your `.visidatarc` and see if that resolves things. 

I'm going to do a little digging in the Visidata repo to see if I need to edit how the plugin is exporting these function or if this is something Visidata itself will need to address.

**Comment by aborruso** [comment]
WOW using mysql works!!!

Now I try with Oracle

**Comment by aborruso** [comment]
It works, thank you very much!!!
